Add table and initial content to readme
vaticle/typedb-driver pull request #453
Opened 2023-09-27 18:31 UTC by izmalk

## What is the goal of this PR?

To add initial content to the main README file in the drivers repository.

## What are the changes implemented in this PR?

Add some initial content and links to readme files, documentation, and source codes for language-specific drivers.

2023-09-27 18:32 UTC, izmalk commented
![Screenshot 2023-09-27 at 19 31 58](https://github.com/vaticle/typedb-driver/assets/48120135/e2cb6b37-5455-4145-b84e-505edfd22c61)

2023-09-28 14:48 UTC, benjaminasmall requested changes

2023-09-28 14:48 UTC, benjaminasmall commented on README.md
> +See the table below for links to README files, documentation, and source codes.
```suggestion
See the table below for links to README files, documentation, and source code.
```

2023-09-28 14:48 UTC, benjaminasmall commented on README.md
> +| C       |    |                                                                               | `c/src` [directory](https://github.com/vaticle/typedb-driver/tree/development/c/src)                 |
Please verify that this is the intended ordering of the five languages.

2023-09-28 14:48 UTC, benjaminasmall commented on README.md
> +| Rust    | [README](https://github.com/vaticle/typedb-driver/tree/development/rust/README.md) |                                                                 | `rust/src` [directory](https://githu
Rust documentation will be out very soon.

2023-09-28 15:22 UTC, izmalk commented on README.md
> +| Rust    | [README](https://github.com/vaticle/typedb-driver/tree/development/rust/README.md) |                                                                 | `rust/src` [directory](https://githu
We can either 
- merge it now without the link and add the link later, when it's ready, or 
- add a link now, expecting it to be eventually working, but showing 404 for now. 
I'd prefer the first variant. What do you think?

2023-09-29 10:18 UTC, izmalk commented on README.md
> +| C       |    |                                                                               | `c/src` [directory](https://github.com/vaticle/typedb-driver/tree/development/c/src)                 |
Double-checked with Haikal, and he adjusted the order. Fixed in https://github.com/vaticle/typedb-driver/pull/453/commits/395640f51a726a661f11f2a2531c8fbb62bbaaea

2023-09-29 11:04 UTC, benjaminasmall commented on README.md
> +| Rust    | [README](https://github.com/vaticle/typedb-driver/tree/development/rust/README.md) |                                                                 | `rust/src` [directory](https://githu
Definitely the former, please.

2023-09-29 11:14 UTC, izmalk commented on README.md
> +| Rust    | [README](https://github.com/vaticle/typedb-driver/tree/development/rust/README.md) |                                                                 | `rust/src` [directory](https://githu
I added a link to rust docs that do not exist yet - https://github.com/vaticle/typedb-driver/pull/453/commits/c3a6e092b602e3e83294e3287478356b384106f9

2023-09-29 11:25 UTC, benjaminasmall approved these changes

2023-09-29 14:40 UTC, flyingsilverfin approved these changes

2023-09-30 12:47 UTC, merged