Fetch
vaticle/typedb-driver pull request #506
Opened 2023-10-31 09:55 UTC by dmitrii-ubskii

**For the title of this PR:** please follow the grammatical rules of a usual publication title, without capitalisation (except for the first letter). Thus, the title should NOT CONTAIN CODE: no dots, no parentheses, no backticks, no brackets, etc. It needs to be distinctive (not detailed) and succinct (not lengthy). Details of this PR will go in the description. **For the description of this PR:** please replace every line in curly brackets ( { like this } ) with an appropriate description following the guidance. Finally, **please remove this paragraph**.

## What is the goal of this PR?

{ In the form of a paragraph (only use bullet points if strictly necessary), please describe the goal of this PR, why they are valuable to achieve, and reference the related GitHub issues. This section will be automatically compiled into the release notes, so please:
  - describe the impact of the change in this PR to the _user_ of this repository (e.g. end user, contributor, developer).
  - describe the new product behaviour in _present tense_, and the old behaviour and how it's been changed in _past tense_.
  - Use the _Royal We_: _"We"_ made changes, not _"I"_ made changes. }

## What are the changes implemented in this PR?

{ Please explain what you implemented, why your changes are the best way to achieve the goal(s) above. Please describe every method, class and package, by explaining:
  - its responsibility, 
  - how it's expected to behave, and 
  - how it relates to the adjacent methods/classes/packages it interacts with. 

This would allow the reviewer to understand your intentions in the code much better. If you're adding new classes, make sure these explanations are also included in the class header comments. Last but not least, please reference the GitHub issues to be automatically closed, such like 'closes #number'. }

2023-10-31 11:46 UTC, dmitrii-ubskii commented on c/src/answer.rs
> +    release(StringIterator(CIterator(box_stream(borrow(concept_map).map.clone().into_keys().map(Ok)))))
`StringIterator` is fallible now that `query_fetch()` returns a stream of JSONs.

2023-10-31 11:46 UTC, dmitrii-ubskii commented on c/src/concept/concept.rs
> +        unreachable!("Attempting to unwrap a non-boolean {:?} as boolean", borrow_as_value(value))
A little nicer message if we crash.

2023-10-31 11:46 UTC, dmitrii-ubskii commented on java/concept/value/ValueImpl.java
> +        if (!isBoolean()) throw new TypeDBDriverException(ILLEGAL_CAST, "boolean");
Guards against crashing on user error

2023-10-31 11:46 UTC, dmitrii-ubskii commented on rust/src/answer/json.rs
> +            JSON::String(string) => write!(f, r#""{string}""#)?,
TODO escape

2023-10-31 11:46 UTC, dmitrii-ubskii commented on rust/tests/BUILD
> +        "@crates//:serde_json",
Serde-json was already used by Cloud, we repurpose it here as a JSON parser for behaviour tests.

2023-10-31 11:46 UTC, dmitrii-ubskii commented on rust/tests/behaviour/mod.rs
> +    pub value_answer: Option<Option<Value>>,
`Some(None)` is equivalent to getting `Numeric::NaN` previously, while `None` means no aggregate query was run.

2023-10-31 11:46 UTC, dmitrii-ubskii commented on rust/tests/behaviour/mod.rs
> +    pub value_answer_group: Vec<ValueGroup>,
A better way to store the latest query result would be to use an enum, but this is out of scope of this PR.

2023-10-31 11:46 UTC, dmitrii-ubskii commented on rust/tests/behaviour/mod.rs
> +    pub value_answer_group: Vec<ValueGroup>,
#507

2023-11-01 11:43 UTC, flyingsilverfin requested changes

2023-11-01 11:43 UTC, flyingsilverfin commented on java/api/answer/JSON.java
> +    }
These should be moved down into a polymorphic implementation

2023-11-01 11:43 UTC, flyingsilverfin commented on java/api/answer/ValueGroup.java
> +    Value value();
This is `Optional<Value>` now right?

2023-11-01 11:43 UTC, flyingsilverfin commented on java/concept/answer/ValueGroupImpl.java
> +    public Value value() {
This should be `Optional` as well

2023-11-01 11:43 UTC, flyingsilverfin commented on java/test/behaviour/util/Util.java
> +        } else if (lhs.isNumber()) {
I believe the non-object and non-array matches can simplfy into `a.equals(b)` using the JSON equality defined on primitives that you've written

2023-11-01 11:45 UTC, flyingsilverfin commented on python/tests/behaviour/background/environment_base.py
> +    context.fetch_answer = None
`fetch_answers`

2023-11-01 11:46 UTC, flyingsilverfin commented on python/typedb/concept/answer/value_group.py
> +    def value(self) -> Value:
This type should indicate it could be `None` right?

2023-11-01 11:47 UTC, flyingsilverfin commented on python/typedb/api/query/query_manager.py
> +    def get_aggregate(self, query: str, options: Optional[TypeDBOptions] = None) -> Promise[Value]:
Should this be `Promise[Value | None]`? Not sure if that's valid syntax...

2023-11-01 15:20 UTC, flyingsilverfin approved these changes

2023-11-01 16:01 UTC, merged