Address translation
vaticle/typedb-driver pull request #624
Opened 2024-04-04 14:28 UTC by dmitrii-ubskii

## Usage and product changes

We allow the user to provide a translation map from the advertised server addresses (now treated as generic server names) to the actual addresses the driver shall use to connect to the cloud instances. We require the user to provide the full mapping.

Example usage:

Python:
```python
with TypeDB.cloud_driver({
            "0.deployment-UUID.cloud.typedb.com:1729": "localhost:11729",
            "1.deployment-UUID.cloud.typedb.com:1729": "localhost:21729",
            "2.deployment-UUID.cloud.typedb.com:1729": "localhost:31729"
        }, credential) as driver:
    pass
```

Rust:
```rust
Connection::new_cloud_with_translation(                                                        
    [                                                                                          
        ("0.deployment-UUID.cloud.typedb.com:1729", "localhost:11729"),
        ("1.deployment-UUID.cloud.typedb.com:1729", "localhost:21729"),
        ("2.deployment-UUID.cloud.typedb.com:1729", "localhost:31729"),
    ].into(),                                                                                  
    credential                                                                                   
)                                                                                              
```

2024-04-04 15:41 UTC, dmitrii-ubskii commented on c/swig/typedb_driver_csharp.swg
> +            for (int i = 0; i < arraySize$csinput; i++)
This broke once we had two input arrays in a function (`connection_open_cloud_translated`). `$csinput` appends the original variable name to `arraySize`, disambiguating the two variables.

2024-04-09 14:57 UTC, dmitrii-ubskii commented on c/src/database.rs
>  }
Should be renamed and rephrased if the Rust changes stick.

2024-04-09 14:57 UTC, dmitrii-ubskii commented on rust/src/common/error.rs
>          5: "Received unrecognized address from the server: {address}.",
TODO

2024-04-09 14:57 UTC, dmitrii-ubskii commented on rust/src/common/info.rs
> -    pub(crate) address: Address,
Not necessary

2024-04-09 14:57 UTC, dmitrii-ubskii commented on rust/src/common/info.rs
> +    pub server_id: String,
TODO docs (if this change is approved)

2024-04-09 14:57 UTC, dmitrii-ubskii commented on rust/src/connection/connection.rs
> -    address: Address,
The only reason for using this was to allow re-fetching the same `ServerConnection` from the overarching `Connection` later. In most cases, the address / server_id is already available.

2024-04-09 14:57 UTC, dmitrii-ubskii commented on rust/src/database/database.rs
> +        F: Fn(ServerDatabase) -> P,
`ServerConnection` is already available through the `ServerDatabase`

2024-04-09 15:15 UTC, flyingsilverfin requested changes

2024-04-09 15:15 UTC, flyingsilverfin commented on rust/tests/integration/network.rs
> +    let connection = Connection::new_cloud_address_map(
Synchronise name

2024-04-09 15:15 UTC, flyingsilverfin commented on rust/src/common/error.rs
> +        24: "Address translation map does not match the advertised server list. Mapped servers not known to the remote server: {unknown:?}. Servers not mapped to addresses: {unmapped:?}.",
```
Address translation map does not match the server's advertised address list. User-provided servers not in the advertised list: {...}; Advertised servers not mapped by user: {...}
```

2024-04-09 15:15 UTC, flyingsilverfin commented on rust/src/connection/connection.rs
> +    pub fn new_cloud_address_map<T, U>(address_translation: HashMap<T, U>, credential: Credential) -> Result<Self>
`new_cloud_with_translation`?

2024-04-11 11:36 UTC, dmitrii-ubskii commented on .factory/automation.yml
> +    test-python-integration:
Unified integration tests across languages.

2024-04-11 11:36 UTC, dmitrii-ubskii commented on cpp/include/typedb/connection/driver.hpp
> +     * received from the TypeDB server(s) to addresses to be used by the driver for connection
Constructor overloads don't seem to get separate docs generated.

2024-04-11 11:36 UTC, dmitrii-ubskii commented on cpp/lib/connection/driver.cpp
> +    auto p = _native::connection_open_core(address.c_str());
Bring in line with declaration.

2024-04-11 11:36 UTC, dmitrii-ubskii commented on csharp/Drivers.cs
> +         * received from the TypeDB server(s) to addresses to be used by the driver for connection
Same as C++, separate docs for overloaded ctors aren't generated.

2024-04-11 11:36 UTC, dmitrii-ubskii commented on python/typedb/driver.py
> +            return _Driver(dict(addresses), credential)
A `Mapping` is an `Iterable`, but not vice versa, so this check must come first.

2024-04-11 13:49 UTC, flyingsilverfin approved these changes

2024-04-11 16:18 UTC, merged